### ISSUE TITLE
Fallback

### ISSUE THREAD

**Issue by Ampretuzo** [simon1573/teddit-redirect#5]
Provide a regular reddit fallback when teddit.net is not responding.  (Maybe with some kind of user notification/interaction.)

**Comment by simon1573** [comment]
Is downtime of teddit.net a frequent issue?

**Comment by Ampretuzo** [comment]
It is not - happened to me only once.  For ~10-30 mins I think.

**Comment by simon1573** [comment]
If it's not a frequent issue I'll let it be. I haven't experienced it more than once myself. If teddit.net goes down it's possible to configure the plugin to point to another instance, configured in the plugin settings.
